language: node_js
node_js:
- '10'
script:
- npm run lint
- npm run coverage
after_success:
- npm run coverage:publish
sudo: required
services:
- docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=lewnelson/lewnelson-com
deploy:
  provider: script
  script: "./scripts/deploy.sh"
  on:
    all_branches: true
