language: node_js
node_js:
- '10'
script:
- npm run eslint
- npm run coverage:ci
after_success:
- npm run coverage:publish
sudo: required
services:
- docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=lewnelson/lewnelson-com
  matrix:
  - secure: MZLDiHAAtTpjbe4WTHKvMivTgJsrvzEvTbkrvxHLbdjtGmBePr79GBafpr8K1I4y1oyxUrgNVC3kJsLm79bg+ETBEhPcyJ2ZwXP2VCBIf/KcNEQK+z8vrZa5yDR6P9yV1ItqwVa13P5q8bq0kLvig7YVInGqoX+sdqeE2NqGJEK+wwAgaCm7pairCUuqxxUx29wSmqVtMNrfnkwSUtyvJZ3HQQsU0bfzoE5rbaNBxBcuornZTw0Cc3lvRU65OcgYBaZGppCrajsnvckdg0uFMbOHptzGHf/qjZbDZNNmaQrDWfoIUTMqKlvVYqRV7GhhrtD60x6fHm+HyZ4ObBpoutnBJmAUmhN9umeRumTBkuAxlrn9bQEjcjxnUp58lEQc3DGQR2i6khvRb3Ke2yry12zHgiLCwD0Zp8/yLaE3LZQW9XDCsw3qpwlJWsFVlYTdVE72lsVXT19bjLkSu5jnZzxpnUAWSAK8Q7e5unbFEtD0ozyrzgGlUPaJW1BfzZtZtYhMDZZhLPf8ZsNwRAZU3yqqeXMKy8A2GPX+bVebR4d9zSR9Oq/P9hGUvi34AMtsBc8fzLmlH/+qjZ0Y9Qnj3jv9sqQ9ToeWAuC94HJm0LtWWJdgVAYUT7cQYOKmvCVS9ck1w9pf9ai1dZRRePs2m/Wt/nZtWgqJ14XvmJPJv84=
  - secure: P11bWoA1HGcFJPDalZMpLvyr0Hr43kLVfoy9bom4cuebwPodpEO4fDVo8ZlOy18n0rJ9tywiz2vDqWiuAhwez8+ghWDsgacJ+TE3/N6OO1mp5DJw6Tcusha0HTRMEDvxAoopUmfuVt/FoMI1F/iQqkitkiCDq9gvbR59jO+4aZ7oCxVwmTNnCug7QS6Gv71yJBBInw6lGMpAfyiut+TyCqeqroAKdMgxJG90zjNOAWnBV+6nS4uC/iE8REnWQWw/1qljjt4so80dCG7R1O3llmEYrF594fJgp0ZpoetkCgei7NgXDejkx5n6qg+XdQe8NRxH+gWRWartAUhfiz7pnsu33x4LhsNwpVhDKbidllxGqGyY+N0vkehCx+C6QlOKHIiCkHQ56qlXToiM9591aRUVWyLivg4DFGzVPWo4mIi9VoWKVBSBzdn3gST0C+wz3C0Hmpj4iGceNSguAL890FtklOIxidZaSRjoVBHxnmekWATt5tRVTXB13P6Oe//poL8vAnvrJ1HXOhFJKbz5jyVEWuC1q7kC4iRblCDQTth7OmkcXR5izBrfHk57oZD5RdEDHMVYhaFJpdqFPs3cynlTEDtRVNUKFnzASp+O980gWVj5vK3H52U0eZ/7k92hkU5UMIYGI7n9grdJyNRw2Q9yotvUbTPyVDS3c2qG+as=
deploy:
- ./scripts/deploy.sh
