language: node_js
node_js:
- '10'
script:
- npm run lint
- npm run coverage
after_success:
- npm run coverage:publish
sudo: required
services:
- docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=lewnelson/lewnelson-com
  - secure: mGYF1YcAays/aWaKH7R60R/xYwYueJ4x5t7oYbEy04126fxSHshRQwJ+MO5ujfLGo95cNcB7jLZjlOlDSGp/jpm5yZCWUS8DTGMFZ06e3i2Gj30IJBfQAMLbv42016RsF+X7DKOvrjgSslDmtf+2EJFWHvoUvrnDV6N63lgTtq3SQeG9x1VWfQtT/+ne6+XIGcT8JQTb+IqBeLQknost3rXUY2igJL7ViyOLhknFNXxpIBm0M3f7fAnQ7YQ6HRzvUWYzOJt7AsUXEcldBZN5XgHceTdZI87hTqABNP0Czlskn5bvqyJJ1aVCQ/rP6WYNupD/JZ6mZI6FOYF7nsJTroBS+OW4bK4yxpyGran8OyCJST18YdEJxyoC2/s5PUfdzezSsaOAca6vNMdb9F+zCrV+2HDwObxUt4p7LEDhIP8MWJrL3JEQsdaCMIV67M3AQS5vPkhjGF+LyP1iPcqjk2Nl75SIhk0Vg0JUPgNA0d7SvRJ3CPIYW6Rb1gJ8EeLemODM9sU/8Gapd5TwbVeIUrM6w8oTCp7TC6+nXBZEjxYODUDRRJV71/CXNV/xHikvB1b9g+hPqqc8PrjJzaWvT77mjWbfXCQxezZq3ekTvsoZ7uB057rDK3PDYdVB9gykXYPpuchXf9uMHFjvzO/Ex3jMfPGel/L75a2A5CuDYxU=
  - secure: jrBfxgh2qh4P4VWtY+xrsvC5jNvwd1Waib097t/XB0sFJRNC32vtoO4I1pief96/LwBKKFJmj+5P7nFZHKhtPaVDDRQhKX4J+gcLeoZkfzWLO38WjiiWjlfCxf+fMKtlp4JtqfFtAZGRcvLyuYMG+etM5A1+J4qREkITaMotyzVkpn+l0Z1ZF85dep/Vt1EG8UQTXb5+4PSYzuxfL27aqe1Pzi2FmZD0uQ7p46+TqQmt10NN4YGjsudf+JyzAG5oxbTI94ITN1Wwy3UpZ5GGg0Pu9GkT1tJeCZN9J1p0t86gZo+kky7A9JIk9DuEtMfk6+JwOy7zivtdWmGWRZLzROQc5JyFO3IAoZDr+JWrrrQ2iHdjGgnnGxrs5wczV5USmDpEthK3fkCbmt381l+aSNG5oo5h2+x67Khp7FI53ddpNhsVDaD4CDqm/0gjJQr1PKy6Y8OkoXhHs4Mj10Buub0M/RQnSFH9IY7o8XTx8o4UeE6qj8VUWNS7SOSBxxsZk2e6gplkQYydsCghYNy05oRk4DBS05t0so/WmO1+MjHA61hz4ijXfQ8FcsOB/49SUNnN29uzjrnECfyKsVK9eQ0EhnpAHDJCYWHUdsLqw2NecENGM5mA3x4b9iCREvIKdpFJR1EI4tIW2weLRlTb/n9YzWOXAM5ZIUW9f2R0NpA=
deploy:
  provider: script
  script: "./scripts/deploy.sh"
  on:
    all_branches: true
