export const UPDATE_DEVICE_TYPE = 'UPDATE_DEVICE_TYPE'
export const CLOSE_NAVIGATION = 'CLOSE_NAVIGATION'
export const OPEN_NAVIGATION = 'OPEN_NAVIGATION'

export const ADD_FEATURE = 'ADD_FEATURE'

export const INCREMENT_LINES_INDEX = 'INCREMENT_LINES_INDEX'
export const INCREMENT_SOCIAL_LINKS_INDEX = 'INCREMENT_SOCIAL_LINKS_INDEX'
