export const UPDATE_DEVICE_TYPE = 'UPDATE_DEVICE_TYPE'
export const CLOSE_NAVIGATION = 'CLOSE_NAVIGATION'
export const OPEN_NAVIGATION = 'OPEN_NAVIGATION'

export const ADD_FEATURE = 'ADD_FEATURE'

export const INCREMENT_LINES_INDEX = 'INCREMENT_LINES_INDEX'

export const TOGGLE_PROJECTS_FILTER = 'TOGGLE_PROJECTS_FILTER'
export const TOGGLE_ALL_PROJECTS_FILTERS = 'TOGGLE_ALL_PROJECTS_FILTERS'
