export const TYPES = {
  EXTRA_SMALL: 0,
  SMALL: 1,
  MEDIUM: 2,
  LARGE: 3
}

export const WIDTHS_TYPES = {
  360: TYPES.EXTRA_SMALL,
  900: TYPES.SMALL,
  1400: TYPES.MEDIUM,
  [-1]: TYPES.LARGE
}
